"""Workspace lifecycle.

A workspace is one project's filesystem, and it is the security boundary. Each
lives at ``<workspaces_root>/<workspace_id>/project`` and nothing outside that
directory is reachable through any documented operation.

The extra ``project/`` level is deliberate: it leaves room for Redstone's own
per-workspace state (snapshots, metadata) as a sibling rather than inside the
directory the agent can write to. The agent cannot reach a sibling, because
every path it supplies is resolved against ``project/``.

Standard library only.
"""

from __future__ import annotations

import os
import re
import shutil
from dataclasses import dataclass
from pathlib import Path

from ..config import Limits
from .paths import PathSecurityError

__all__ = ["WorkspaceError", "Workspace", "WorkspaceManager"]

# Workspace ids are generated by Redstone, never supplied by a caller. This is
# still validated, because an id reaching the filesystem from an API path
# parameter would otherwise be a traversal vector.
_ID = re.compile(r"^[A-Za-z0-9_-]{3,64}$")


class WorkspaceError(Exception):
    """A workspace could not be created, found, or removed."""


def _remove_link_entry(function, path, exc) -> None:
    """rmtree error handler for entries a sandbox created.

    A Linux symlink written by a sandboxed process onto a Windows bind mount
    (npm creates them routinely, e.g. node_modules/.bin/*) appears on the
    host as a reparse point that reports a directory mode; rmtree tries to
    descend into it and cannot open it (WinError 1920). Removing the entry
    itself works -- rmdir for directory-type links, remove for file-type --
    and removes only the link, never its target. Anything else re-raises.
    """
    if not os.path.lexists(path):
        return   # already removed (e.g. by this handler, one step earlier)
    for remover in (os.rmdir, os.remove):
        try:
            remover(path)
            return
        except FileNotFoundError:
            return
        except OSError:
            continue
    raise exc


@dataclass(frozen=True, slots=True)
class Workspace:
    """One project's isolated filesystem."""

    id: str
    root: Path            # <workspaces_root>/<id>
    project_root: Path    # <workspaces_root>/<id>/project

    @property
    def internal_root(self) -> Path:
        """Redstone's own state for this workspace. Never agent-writable."""
        return self.root / ".redstone"

    def exists(self) -> bool:
        return self.project_root.is_dir()


class WorkspaceManager:
    """Creates, finds and destroys workspaces beneath a single root."""

    def __init__(self, workspaces_root: Path | str, limits: Limits | None = None) -> None:
        self.workspaces_root = Path(workspaces_root).resolve()
        self.limits = limits or Limits()

    # ------------------------------------------------------------------ paths

    def _validate_id(self, workspace_id: str) -> str:
        if not isinstance(workspace_id, str) or not _ID.match(workspace_id):
            # Rejects "..", "../x", absolute paths and separators in one rule.
            raise WorkspaceError("invalid workspace id")
        return workspace_id

    def path_for(self, workspace_id: str) -> Path:
        workspace_id = self._validate_id(workspace_id)
        candidate = (self.workspaces_root / workspace_id).resolve()

        # Belt and braces: even with a validated id, confirm containment.
        if candidate.parent != self.workspaces_root:
            raise WorkspaceError("workspace id escapes the workspaces root")

        return candidate

    # -------------------------------------------------------------- lifecycle

    def create(self, workspace_id: str) -> Workspace:
        root = self.path_for(workspace_id)

        if root.exists():
            raise WorkspaceError("workspace already exists")

        project_root = root / "project"
        project_root.mkdir(parents=True)
        (root / ".redstone").mkdir()

        return Workspace(id=workspace_id, root=root, project_root=project_root)

    def get(self, workspace_id: str) -> Workspace:
        root = self.path_for(workspace_id)
        workspace = Workspace(id=workspace_id, root=root, project_root=root / "project")

        if not workspace.exists():
            raise WorkspaceError("workspace not found")

        return workspace

    def exists(self, workspace_id: str) -> bool:
        try:
            return self.get(workspace_id).exists()
        except WorkspaceError:
            return False

    def destroy(self, workspace_id: str) -> None:
        """Remove a workspace and everything in it.

        Refuses to delete anything that is not a direct child of the
        workspaces root, so a bug elsewhere cannot turn this into an arbitrary
        recursive delete.
        """
        root = self.path_for(workspace_id)

        if not root.exists():
            return

        if root.parent != self.workspaces_root:
            raise WorkspaceError("refusing to remove a path outside the workspaces root")

        shutil.rmtree(root, onexc=_remove_link_entry)

    def list_ids(self) -> tuple[str, ...]:
        if not self.workspaces_root.is_dir():
            return ()
        return tuple(
            sorted(
                entry.name
                for entry in self.workspaces_root.iterdir()
                if entry.is_dir() and _ID.match(entry.name)
            )
        )

    # ------------------------------------------------------------- isolation

    def assert_isolated(self, workspace_id: str, candidate: Path) -> None:
        """Raise unless `candidate` really lies inside this workspace's project.

        Used at boundaries where a path arrived from somewhere other than
        `resolve`, so that cross-workspace access fails loudly.
        """
        from .paths import is_within

        workspace = self.get(workspace_id)
        if not is_within(candidate, workspace.project_root):
            raise PathSecurityError("path is outside the workspace")
